GET http://localhost:4000/api/services

###

GET http://localhost:4000/api/services/63374185d4c49070a54bb87e

###

POST http://localhost:4000/api/services
Content-Type: application/json

{
    "title": "AC Fix",
    "main_description": "I will fix your AC",
    "price": 3000
}

###

POST http://localhost:4000/api/services/63374185d4c49070a54bb87e

###

PATCH  http://localhost:4000/api/services/63373a087e66ff42cff58ce1
Content-Type: application/json

{
    "price": 2000
}